### ISSUE TITLE
single end RNAseq validation dataset

### ISSUE THREAD

**Issue by rbatorsky** [griffithlab/rnaseq_tutorial_v1#1]
Hello,
I've found your tutorial very helpful, especially regarding paired end RNAseq validation data.
Do you know of a public source of single-end RNAseq data with ERCC spike in that we can use for pipeline validation? 
Thank you in advance,
Rebecca

**Comment by malachig** [comment]
I think this workflow should work with single end data with only trivial
modifications.

Malachi

**Comment by rbatorsky** [comment]
Thank you for your response. Yes, the workflow is easy to adapt. I am looking for standard samples, such as ERCC spike-in, in order to validate the quality of SE vs. PE. I would appreciate any advice on where to find these. Thanks again.

**Comment by malachig** [comment]
I’m still not understanding the question.  The ERCC spike-in is generally
added at the earliest possible step in library construction (e.g. right to
the total RNA). It should work fine from that point whether you do single
or paired-end sequencing.

You say you are looking for standard “samples”.  Do you mean you want data
that is already generated?  For example, the same samples, with the same
spike-ins but then used to create single or paired-end data?

In any case, the library construction steps are essentially the same for SE
vs. PE.  The difference is how you sequence them.  If you are interested in
how SE vs PE affects analyses, you might just do this in silico.  Start
with paired end data and simply drop one pair from every read.  You can
also determine the effects of read length by trimming the reads.

**Comment by rbatorsky** [comment]
Thanks, yes you have understood correctly. I am ideally looking for PE and SE preexisting datasets that have been generated for the same sample. We don't have the ability to generate them in my lab, but wish to study the differences in data quality. I was not aware that the library prep was the same for both sequencing methods. I will check on this, and if so we can just select a single end from the paired end spike-in data. Thanks again.
